In [1]:
using LinearAlgebra
using Plots

In [2]:
α=2

2

In [3]:
α^2

4

In [4]:
1+eps() ≈ 1

true

In [5]:
n = 10
m = 30 
A = rand(m,n);

In [38]:
function QR(A)
    Q = zeros(size(A)) #(m,n)
    R = zeros(size(A,2),size(A,2)) #(n,n)

    for i = 1:n
        for j = 1:i-1
            R[j,i] = Q[:,j]'A[:,i]
            println(R)
        end
        p = A[:,i] - Q[:,1:i-1]*R[1:i-1,i]
        R[i,i]=norm(p)
        if abs(R[i,i])<0.00000000001
            println("Rii cercano 0")
        end
        Q[:,i] = p/R[i,i]
    end
    return Q,R
end

QR (generic function with 1 method)

In [37]:
Q, R = QR(rand(2,2))
R

uno
[0.0 0.0; 0.0 0.0]
2
uno
[0.019612609727534033 0.0; 0.9998076542713981 0.0]
[0.8914518484865129 0.2529509860870179; 0.0 0.0]
2
uno
[0.019612609727534033 0.9998076542713981; 0.9998076542713981 -0.01961260972753397]


LoadError: BoundsError: attempt to access 2×2 Matrix{Float64} at index [1:2, 3]

In [13]:
opnorm(A-Q*R)

5.105868524331349e-16

In [14]:
opnorm(Q'Q-UniformScaling(1))

3.87652831475042e-15

In [15]:
T=[1 0;0 1 ]

2×2 Matrix{Int64}:
 1  0
 0  1

In [16]:
T+UniformScaling(2)

2×2 Matrix{Int64}:
 3  0
 0  3

In [17]:
@time Aqr=qr(A)

  0.195644 seconds (124.63 k allocations: 6.742 MiB, 28.71% gc time, 98.29% compilation time)


LinearAlgebra.QRCompactWY{Float64, Matrix{Float64}}
Q factor:
30×30 LinearAlgebra.QRCompactWYQ{Float64, Matrix{Float64}}:
 -0.211018   -0.0352995     0.117477   -0.239168   …  -0.16908    -0.181483
 -0.129794   -0.32625       0.248706    0.0968155     -0.0625078   0.308187
 -0.189087   -0.220988     -0.115848    0.0830908     -0.134437   -0.185919
 -0.24125     0.0655345    -0.0595495  -0.417304      -0.0086168   0.143188
 -0.248298   -0.14273       0.371581    0.0871158     -0.181507    0.032916
 -0.0364259  -0.15741      -0.396856    0.109127   …  -0.0241534   0.0649402
 -0.0554089  -0.268172      0.0852487   0.273254      -0.119503   -0.352934
 -0.26065     0.30809       0.137215    0.041021       0.0120578   0.0386496
 -0.184553   -0.0800115     0.0290337  -0.0510811     -0.317342    0.0742788
 -0.130444   -0.0924223    -0.118482    0.19224       -0.16506     0.0883887
 -0.039454   -0.131723     -0.0680565   0.329111   …   0.0559904  -0.059585
 -0.277415    0.203416      0.188644  

In [18]:
opnorm(A-Aqr.Q*Aqr.R)

2.5409495165237745e-15

In [19]:
opnorm(Aqr.Q'Aqr.Q-UniformScaling(1))

1.0072593312523528e-15

In [22]:
T1=[1 1; 1 1; 1 1]
T2=[1;1;1]
T=[T1 T2]

3×3 Matrix{Int64}:
 1  1  1
 1  1  1
 1  1  1

In [23]:
Int(20/2)

10

In [26]:
n = 20
m = 30 
A1 = rand(m,Int(n/2));
A2=A1+0.0000000001*rand(m,Int(n/2));
opnorm(A1-A2)
A3=[A1 A2];
#A3=rand(m,n)

In [27]:
Q2, R2 = QR(A3);

In [28]:
opnorm(A3-Q2*R2)

8.258056218067943e-16

In [29]:
opnorm(Q2'Q2-UniformScaling(1))

9.000000000300775

In [30]:
diag(R2)

20-element Vector{Float64}:
 3.736710973032969
 1.6876686644072467
 1.8710366346078198
 1.5948257508818313
 1.6819485051176848
 1.6717121511352266
 1.6144502913781063
 1.4236237333966337
 1.5678220608449374
 1.4688198642569716
 1.4870943154031674e-10
 1.415066242036566e-5
 9.60851739935723e-6
 7.931046835727973e-6
 2.6594332901746154e-5
 1.4080244613845847e-5
 5.166141401516387e-5
 0.00013026451152991773
 5.5098152899515985e-5
 7.332807466008145e-5